// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RInrx5FYwSzfnT5mJnQn2qoz4EmBlow',
    appId: '1:446777296937:web:c4a96e3221947dc4407438',
    messagingSenderId: '446777296937',
    projectId: 'community-hero-app-500611',
    authDomain: 'community-hero-app-500611.firebaseapp.com',
    storageBucket: 'community-hero-app-500611.firebasestorage.app',
    measurementId: 'G-42J4DHF4X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4tMlteF3msdL7krkAg6Bvvf4z1f81Vc',
    appId: '1:446777296937:android:ffa1631355720294407438',
    messagingSenderId: '446777296937',
    projectId: 'community-hero-app-500611',
    storageBucket: 'community-hero-app-500611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6eWaJaDpC9rZW5xt6oUYlrbvSV39bhnA',
    appId: '1:446777296937:ios:9795d9a36f86c65e407438',
    messagingSenderId: '446777296937',
    projectId: 'community-hero-app-500611',
    storageBucket: 'community-hero-app-500611.firebasestorage.app',
    iosBundleId: 'com.example.civicReporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6eWaJaDpC9rZW5xt6oUYlrbvSV39bhnA',
    appId: '1:446777296937:ios:9795d9a36f86c65e407438',
    messagingSenderId: '446777296937',
    projectId: 'community-hero-app-500611',
    storageBucket: 'community-hero-app-500611.firebasestorage.app',
    iosBundleId: 'com.example.civicReporter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1RInrx5FYwSzfnT5mJnQn2qoz4EmBlow',
    appId: '1:446777296937:web:0dc860f9c789588a407438',
    messagingSenderId: '446777296937',
    projectId: 'community-hero-app-500611',
    authDomain: 'community-hero-app-500611.firebaseapp.com',
    storageBucket: 'community-hero-app-500611.firebasestorage.app',
    measurementId: 'G-YNJCB615LT',
  );
}
