import 'dart:io' show Platform;
import 'dart:ui' show ImageFilter;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show HapticFeedback;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'firebase_options.dart';
import 'screens/report_issue_screen.dart';
import 'screens/live_map_screen.dart';
import 'screens/profile_screen.dart';
import 'screens/insights_screen.dart';
import 'screens/auth_gate.dart';
import 'screens/admin_dispatch_screen.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'widgets/scale_interactive_widget.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Gracefully initialize Firebase using configurations generated by FlutterFire CLI
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    // Initialize analytics if initialization succeeded
    FirebaseAnalytics.instance.logAppOpen();
  } catch (e) {
    debugPrint('Firebase initialization skipped/failed: $e');
  }

  runApp(const CivicReporterApp());
}

// ─── GovTech Brand Tokens ──────────────────────────────────────────────────
class AppColors {
  static const navyBlue    = Color(0xFF1E3A8A); // authority & trust
  static const navyLight   = Color(0xFF2D4FAD);
  static const navyDark    = Color(0xFF162D6B);
  static const orange      = Color(0xFFF97316); // hazard & urgency
  static const orangeLight = Color(0xFFFF9944);
  static const bgGray      = Color(0xFFF3F4F6);
  static const surface     = Colors.white;
  static const textDark    = Color(0xFF0F172A);
  static const textMid     = Color(0xFF475569);
  static const textLight   = Color(0xFF94A3B8);
  static const success     = Color(0xFF16A34A);
  static const warning     = Color(0xFFD97706);
  static const danger      = Color(0xFFDC2626);
}

class CivicReporterApp extends StatelessWidget {
  const CivicReporterApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Civic Reporter',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        fontFamily: 'Roboto',
        primaryColor: AppColors.navyBlue,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary:         AppColors.navyBlue,
          onPrimary:       Colors.white,
          primaryContainer: Color(0xFFDBE8FF),
          onPrimaryContainer: AppColors.navyDark,
          secondary:       AppColors.orange,
          onSecondary:     Colors.white,
          secondaryContainer: Color(0xFFFFEDDE),
          onSecondaryContainer: Color(0xFF7A3000),
          surface:         Colors.white,
          onSurface:       AppColors.textDark,
          error:           AppColors.danger,
          onError:         Colors.white,
          errorContainer:  Color(0xFFFFE4E4),
          onErrorContainer: AppColors.danger,
          outline:         Color(0xFFCBD5E1),
          outlineVariant:  Color(0xFFE2E8F0),
          shadow:          Colors.black,
          scrim:           Colors.black,
          inverseSurface:  AppColors.navyDark,
          onInverseSurface: Colors.white,
          inversePrimary:  Color(0xFF93ADEF),
        ),
        scaffoldBackgroundColor: AppColors.bgGray,
        cardTheme: CardThemeData(
          color: Colors.white,
          elevation: 0,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.navyBlue,
          foregroundColor: Colors.white,
          elevation: 0,
          scrolledUnderElevation: 0,
          centerTitle: false,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 18,
            fontWeight: FontWeight.w700,
            letterSpacing: -0.3,
          ),
          iconTheme: IconThemeData(color: Colors.white),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: AppColors.orange,
            foregroundColor: Colors.white,
            elevation: 0,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            textStyle: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: AppColors.navyBlue,
            side: const BorderSide(color: AppColors.navyBlue, width: 1.5),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFFE2E8F0)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: AppColors.navyBlue, width: 2),
          ),
        ),
        snackBarTheme: SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
          backgroundColor: AppColors.navyDark,
          contentTextStyle: const TextStyle(color: Colors.white),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        ),
        progressIndicatorTheme: const ProgressIndicatorThemeData(
          color: AppColors.orange,
          linearTrackColor: Color(0xFFE2E8F0),
        ),
      ),
      home: const AuthGate(),
    );
  }
}

class MainContainer extends StatefulWidget {
  const MainContainer({super.key});

  @override
  State<MainContainer> createState() => _MainContainerState();
}

class _MainContainerState extends State<MainContainer> {
  int _currentIndex = 0;
  String _userName = 'Guest User';
  dynamic _userListener;
  bool _isAdmin = false;

  // Use IndexedStack to preserve state of screens (especially the live map screen)
  final List<Widget> _screens = [
    const ReportIssueScreen(),
    const LiveMapScreen(),
    const InsightsScreen(),
    const AdminDispatchScreen(),
  ];

  @override
  void initState() {
    super.initState();
    _loadUser();
  }

  @override
  void dispose() {
    _userListener?.cancel();
    super.dispose();
  }

  void _loadUser() {
    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        setState(() {
          _userName = user.displayName ?? (user.isAnonymous ? 'Guest User' : 'Citizen');
        });
        
        // Listen to live updates from Firestore
        _userListener = FirebaseFirestore.instance.collection('users').doc(user.uid).snapshots().listen((doc) {
          if (doc.exists && doc.data() != null && mounted) {
            final data = doc.data()!;
            setState(() {
              if (data['name'] != null) {
                _userName = data['name'];
              }
              _isAdmin = data['role'] == 'admin';
            });
          }
        });
      }
    } catch (e) {
      debugPrint('Firebase not initialized in MainContainer: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    final screens = _isAdmin ? _screens : _screens.sublist(0, 3);

    return Scaffold(
      body: Stack(
        children: [
          IndexedStack(
            index: _currentIndex >= screens.length ? 0 : _currentIndex,
            children: screens,
          ),
          Positioned(
            top: MediaQuery.of(context).padding.top + 6,
            right: 16,
            child: ScaleInteractiveWidget(
              onTap: () async {
                await Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => const ProfileScreen()),
                );
              },
              child: Container(
                padding: const EdgeInsets.all(2),
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  border: Border.all(color: Colors.white, width: 2),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.1),
                      blurRadius: 8,
                      spreadRadius: 1,
                    )
                  ],
                ),
                child: CircleAvatar(
                  radius: 20,
                  backgroundColor: AppColors.navyLight,
                  backgroundImage: (!kIsWeb && Platform.environment.containsKey('FLUTTER_TEST'))
                      ? null
                      : NetworkImage(
                          'https://api.dicebear.com/7.x/avataaars/png?seed=${Uri.encodeComponent(_userName)}',
                        ),
                  child: (!kIsWeb && Platform.environment.containsKey('FLUTTER_TEST'))
                      ? const Icon(Icons.person, color: Colors.white, size: 20)
                      : null,
                ),
              ),
            ),
          ),
        ],
      ),
      bottomNavigationBar: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 10,
              offset: const Offset(0, -4),
            )
          ],
        ),
        child: ClipRRect(
          child: BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
            child: BottomNavigationBar(
              currentIndex: _currentIndex >= screens.length ? 0 : _currentIndex,
              onTap: (index) {
                HapticFeedback.selectionClick();
                setState(() {
                  _currentIndex = index;
                });
                // Try to log screen view to Firebase Analytics
                try {
                  String screenName = 'ReportIssue';
                  if (index == 1) screenName = 'LiveMap';
                  if (index == 2) screenName = 'Insights';
                  if (index == 3) screenName = 'Dispatch';
                  FirebaseAnalytics.instance.logEvent(
                    name: 'screen_view',
                    parameters: {
                      'screen_name': screenName,
                    },
                  );
                } catch (_) {}
              },
              backgroundColor: Colors.white,
              selectedItemColor: AppColors.orange,
              unselectedItemColor: const Color(0xFF94A3B8),
              selectedLabelStyle: const TextStyle(
                fontWeight: FontWeight.w700,
                fontSize: 11,
                letterSpacing: 0.2,
              ),
              unselectedLabelStyle: const TextStyle(fontSize: 11),
              iconSize: 24,
              elevation: 0,
              type: BottomNavigationBarType.fixed,
              items: [
                const BottomNavigationBarItem(
                  icon: Icon(Icons.campaign_outlined),
                  activeIcon: Icon(Icons.campaign_rounded),
                  label: 'Report',
                ),
                const BottomNavigationBarItem(
                  icon: Icon(Icons.public_outlined),
                  activeIcon: Icon(Icons.public_rounded),
                  label: 'Live Map',
                ),
                const BottomNavigationBarItem(
                  icon: Icon(Icons.bar_chart_outlined),
                  activeIcon: Icon(Icons.bar_chart_rounded),
                  label: 'Insights',
                ),
                if (_isAdmin)
                  const BottomNavigationBarItem(
                    icon: Icon(Icons.local_police_outlined),
                    activeIcon: Icon(Icons.local_police),
                    label: 'Dispatch',
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
